### ISSUE TITLE
Replace dummy data in What's New display

### ISSUE THREAD

**Issue by joeb37** [CS599-MEDLINE/pubminer-ui-investigation#7] opened 2018-03-16 03:46 UTC
The "What's New" display is showing canned data. Once we have developed the mechanism for updating the back end database, this section will need to be fully fleshed out.

**Comment by garzillo** [comment] 2018-03-18 22:26
@joeb37 is the idea to have the newest articles that we've pulled data out of or just the newest publications on pubmed?

**Comment by joeb37** [comment] 2018-03-19 02:02
I believe the intent here is to display the latest items that we've pulled in to our database.  Our data gathering methods have changed since this display was originally proposed in Milestone 1, so some adjustment of what's displayed or what we call it may be in order.

**Comment by freshottr** [comment] 2018-04-18 11:53
This the same as #66 right?

**Comment by freshottr** [comment] 2018-04-21 21:44
Duplicate of #66

**Closed by freshottr** 2018-04-21 21:44 UTC
Labels: improvement
